name: Destruir infraestrutura

on:
    workflow_dispatch:

env:
  AWS_REGION: sa-east-1
  CLUSTER_NAME: tech-challenge-cluster

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Inicializar Terraform
        run: terraform init -upgrade
   
      - name: Inicializar Plano
        run: terraform plan
  
      - name: Atualizar configuração do Kube
        run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Verificar recursos em execução no cluster
        run: |
          echo "Verificando recursos em execução no cluster..."
          PODS=$(kubectl get pods --all-namespaces -o json | jq '.items | length')
          SERVICES=$(kubectl get services --all-namespaces -o json | jq '.items | length')
          DEPLOYMENTS=$(kubectl get deployments --all-namespaces -o json | jq '.items | length')
          
          if [ "$PODS" -gt 4 ] || [ "$SERVICES" -gt 2 ] || [ "$DEPLOYMENTS" -gt 1 ]; then
            echo "Atenção: Existem recursos em execução no cluster!"
            echo "Pods: $PODS"
            echo "Services: $SERVICES"
            echo "Deployments: $DEPLOYMENTS"
            echo "Por favor, revise e remova manualmente estes recursos antes de prosseguir com a destruição da infraestrutura."
            exit 1
          else
            echo "Nenhum recurso em execução encontrado. Prosseguindo com a destruição da infraestrutura."
          fi
          
      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false